[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = ["E9", "F63", "F7", "F82"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_unused_ignores = false
show_error_codes = true
explicit_package_bases = true
disable_error_code = "arg-type,attr-defined,call-arg,operator,no-redef,var-annotated,union-attr"
files = "overlay_plugin/overlay_api.py, overlay_plugin/legacy_tcp_server.py, prefix_entries.py"
